package io.github.skylerdev.McWiki;

import org.json.simple.JSONArray;

public class BookDefaults {

    @SuppressWarnings("unchecked")
    public static String titlePage(String atitle, String aurl) {
        JSONArray titlepage = new JSONArray();
        titlepage.add("");

        MCJson title = new MCJson("\n   " + atitle, "dark_aqua");
        title.setBold(true);
        titlepage.add(title);

        titlepage.add("\n");

        MCJson subtitle = new MCJson("  Generated by McWiki", "dark_gray");
        titlepage.add(subtitle);

        titlepage.add("\n\n\n");

        MCJson sup = new MCJson("Displaying 1 p per page. Images and table data omitted.", "gray");
        titlepage.add(sup);
        titlepage.add("\n\n\n");

        MCJson link = new Link("     [Full Article]", aurl);
        link.setColor("aqua");
        titlepage.add(link);

        return titlepage.toString();
    }

    public static String endPage() {

        MCJson title = new MCJson(" >> End of Article");
        title.setColor("dark_aqua");

        return title.toString();

    }

    public static String debugPage() {
        MCJson debug = new MCJson("McWiki 2.1. Made with love by skylerdev <3");

        return debug.toString();
    }
}
